<?xml version="1.0"?>

<!DOCTYPE newspaper [
<!ELEMENT newspaper (article+)>

<!ELEMENT article (headline, byline, lead, body, notes)>
<!ATTLIST article author CDATA #REQUIRED>

<!ELEMENT headline (#PCDATA)>
<!ELEMENT byline (#PCDATA)>
<!ELEMENT lead (#PCDATA)>
<!ELEMENT body (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
]>

<newspaper>
    <article author="Ram">
        <headline>News Title</headline>
        <byline>Ram</byline>
        <lead>Introduction</lead>
        <body>Main content</body>
        <notes>Extra notes</notes>
    </article>
</newspaper>
