=== Prajwal-Chaulagain/Fifth-Semester/Web Technology/Unit-5_Extensible_Markup_Language(XML)/Note.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.a.com" xmlns="http://www.a.com"
elementFormDefault="qualified">
    <xs:element name ="note"> <!-- Root element-->
       <xs:complexType>
          <xs:sequence>
             <xs:element name="id" type="xs:integer"></xs:element>
             <xs:element name="name" type="xs:string"></xs:element>
             <xs:element name="address" type="xs:string"></xs:element>
             <xs:element name="email" type="xs:string" maxOccurs="5" minOccurs="2"></xs:element>
             <xs:element name="dob" type="xs:date"></xs:element>
             <xs:element name="pi" type="xs:decimal" fixed="3.14"></xs:element>
          </xs:sequence>
          <xs:attribute name="age" type="xs:int" fixed="45"></xs:attribute>
       </xs:complexType>
    </xs:element>
</xs:schema>

=== Prajwal-Chaulagain/Fifth-Semester/Web Technology/Unit-5_Extensible_Markup_Language(XML)/Student.xml
<?xml version="1.0"?>
<note xmlns="http://www.a.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.a.com note.xsd" age="45">
  <id>101</id>
  <name>Prajwal</name>
  <address>Chapagaun</address>
  <email>prajwal@gmail.com</email> 
  <email>prajwal@gmail.com</email>
  <dob>2003-02-11</dob>
  <pi>3.14</pi>

</note>
